// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package media_sql

import (
	"github.com/google/uuid"
)

type Medium struct {
	ID      int32     `json:"id"`
	MediaID uuid.UUID `json:"mediaId"`
	OwnerID int32     `json:"ownerId"`
}
