// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package media_sql

import (
	"time"

	"github.com/google/uuid"
)

type Medium struct {
	MediaID                int32     `json:"mediaId"`
	ExternalUuidFull       uuid.UUID `json:"externalUuidFull"`
	ExternalUuidCompressed uuid.UUID `json:"externalUuidCompressed"`
	UserID                 int32     `json:"userId"`
	CompressionStatus      string    `json:"compressionStatus"`
	UploadDate             time.Time `json:"uploadDate"`
	IsActive               bool      `json:"isActive"`
}
