// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package users

import (
	"github.com/google/uuid"
)

type User struct {
	UserID         int32         `json:"userId"`
	Username       string        `json:"username"`
	Email          string        `json:"email"`
	Firstname      string        `json:"firstname"`
	Lastname       string        `json:"lastname"`
	ProfileImageID uuid.NullUUID `json:"profileImageId"`
}
