// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package users

import ()

type User struct {
	ID        int32
	Username  string
	Email     string
	Firstname string
	Lastname  string
}
