version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "443:443"
      - "8080:8080"
    depends_on:
      - authentication-service

  # minio:
  #   image: minio/minio
  #   command: server --address ":9000" --console-address ":9001" /data
  #   ports:
  #     - "9001:9001"
  #   environment:
  #     MINIO_ACCESS_KEY: minio
  #     MINIO_SECRET_KEY: minio123
  #   volumes:
  #     - ${PWD}/minio-data:/data
     
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=bernardn
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=postgres
      - APP_DB_PASS=password
      - AUTH_DB_NAME=authentication_service
      - PGUSER=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database-init:/docker-entrypoint-initdb.d/

  authentication-service:
    build:
      context: ../authentication_service
      dockerfile: ./authentication_service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
            limits:
              cpus: "1"
              memory: 1024M
            reservations:
              cpus: "0.25"
              memory: 128M
    environment:
      postgresDsn: "user=postgres password=password host=postgres dbname=authentication_service port=5432 sslmode=disable"
      jwtSecret: "qwertyuiopasdfghjklzxcvbnm123456"
      port: ":8080"
    depends_on:
      - postgres

