// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package users

import ()

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}
