// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package posts

import (
	"database/sql"
	"time"
)

type Post struct {
	ID        int32         `json:"id"`
	UserID    int32         `json:"userId"`
	Username  string        `json:"username"`
	Body      string        `json:"body"`
	MediaID   sql.NullInt32 `json:"mediaId"`
	CreatedAt time.Time     `json:"createdAt"`
}
